### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by ENDER1355** [THEREALWWEFAN231/TunnelMC#18]
im too lazy to compile

i want to troll mcpe players on java with wurst

**Comment by NathanKassab** [comment]
The github issues section isn't the place to ask, either compile it yourself or don't use it. Using github issues to complain that the developers who are working for free aren't fast enough is rude

**Comment by ENDER1355** [comment]
> The github issues section isn't the place to ask, either compile it yourself or don't use it. Using github issues to complain that the developers who are working for free aren't fast enough is rude

sry bro i didn't meant to annoy them
