### ISSUE TITLE
Can´t build the mod

### ISSUE THREAD

**Issue by UseUser123321** [THEREALWWEFAN231/TunnelMC#23]
Gives me a error when building the mod

**Comment by NathanKassab** [comment]
We can't help you if you don't tell us what's wrong, "it won't work" doesn't give us any useful information

**Comment by UseUser123321** [comment]
ok

**Comment by UseUser123321** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'TunnelMC'.
> Failed to provide com.mojang:minecraft:1.16.5 : java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 7s

**Comment by UseUser123321** [comment]
i will create other issue
