### ISSUE TITLE
Crash when starting the game due to a probably wrong/missing/typo'ed definition

### ISSUE THREAD

**Issue by Snivine** [THEREALWWEFAN231/TunnelMC#3]
So, I know that I shouldn't be able to try the mod but I just build it and decided to try it out, but it crashes my game due to some NukkitX class defition thing, anyway you'll probably just close this since it's probably my fault for trying the mod by myself, but just to inform you xd
crash report here: https://paste.ee/p/QuS27

**Comment by THEREALWWEFAN231** [comment]
gradlew build currently doesn't work, you have to use it in an ide, I'll fix it sometime.

**Comment by THEREALWWEFAN231** [comment]
Should be fixed in 63ca9fbd719f70c4aba10ab34e95df45531e4dfa
