### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by Mythbusters123** [THEREALWWEFAN231/TunnelMC#9]

**Comment by THEREALWWEFAN231** [comment]
No, I plan to work on it soon, possibly this month, I need/want to get somethings working correctly, chunk loading mainly, then work on other things like inventory "management".

**Comment by Mythbusters123** [comment]
Alright, I have been pointed to this project as I want to play hive with Java edition!

**Comment by Camotoy** [comment]
I do have some changes in my fork if you do pick up this project, such as armor support and limited biome support. I'm happy to PR if you want but it does deviate from the codestyle of the project.
